#!/bin/bash

# dotfiles path
pdot = "/home/mluk/.config/dotfiles"

# software install ubuntu WSL
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
sudo apt-add-repository https://cli.github.com/packages

sudo apt update

sudo apt install neovim ranger gh mc zsh tmux

# configuration files 
# bashrc 
rm ~/.bashrc ~/.bash_profile
ln -s "$pdot/.bashrc" ~/.bashrc
ln -s "$pdot/.bash_profile" ~/.bash_profile

# tmux
rm ~/.tmux.conf
ln -s "$pdot/.tmux.conf" ~/.tmux.conf

# zsh
rm ~/.zshrc
ln -s "$pdot/.zshrc" ~/.zshrc
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# git
rm ~/.gitconfig
ln -s "$pdot/.gitconfig" ~/.gitconfig

# dircolors
rm ~/.dircolors
ln -s "$pdot/.dircolors" ~/.dircolors

# vim
if [ ! -d "~/.config/nvim"]; then
	mkdir -p ~/.config/nvim
else
	rm ~/.config/nvim/init.vim ~/.config/nvim/vimscripts
fi
ln -s "$pdot/init.vim" ~/.config/nvim/init.vim
ln -s "$pdot/vimscripts" ~/.config/nvim/vimscripts
neovim +PlugInstall

source ~/.zshrc
